environments:
  kind:
    kubeContext: kind-kind-cluster
    values:
      - kind.values.yaml
---
repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: emberstack
    url: https://emberstack.github.io/helm-charts

releases:
  - name: metrics-server
    namespace: metrics-server
    chart: metrics-server/metrics-server
    version: 3.12.0
    values:
      - ./metrics-server.values.yaml.gotmpl

  - name: nginx-ingress
    namespace: nginx
    chart: oci://ghcr.io/nginxinc/charts/nginx-ingress
    version: 1.1.3
    values:
      - ./nginx-ingress.values.yaml.gotmpl

  - name: cert-manager-crds
    namespace: cert-manager
    chart: ./cert-manager-crds
    version: 1.14.3

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.14.3
    needs:
      - cert-manager-crds
    values:
      - ./cert-manager.values.yaml.gotmpl

  - name: cert-manager-csi-driver
    namespace: cert-manager
    chart: jetstack/cert-manager-csi-driver
    version: 0.7.1
    needs:
      - cert-manager
    values:
      - ./cert-manager-csi-driver.yaml.gotmpl

  - name: trust-manager
    namespace: cert-manager
    chart: jetstack/trust-manager
    version: 0.8.0
    needs:
      - cert-manager
    values:
      - ./trust-manager.values.yaml.gotmpl

  - name: reflector
    namespace: emberstack
    chart: emberstack/reflector
    version: 7.1.256
    values:
      - ./reflector.values.yaml.gotmpl
