environments:
  kind:
    kubeContext: kind-kind-cluster
---
helmfiles:
  - cert-manager-crds-helmfile.yaml
  - metrics-server/helmfile.yaml
  - nginx-ingress/helmfile.yaml
  - cert-manager/helmfile.yaml
  - reloader/helmfile.yaml
  - reflector/helmfile.yaml
  - redis-cluster/helmfile.yaml
