environments:
  kind:
    kubeContext: kind-kind-cluster
---
helmfiles:
  - crds-helmfile.yaml
  - metrics-server/helmfile.yaml
  - nginx-ingress/helmfile.yaml
  - cert-manager/helmfile.yaml
  - reloader/helmfile.yaml
  - reflector/helmfile.yaml
  # disable redis-cluster due to an unresolved error causes the cluster nodes
  # can be readied.
  #- redis-cluster/helmfile.yaml
  - redis/helmfile.yaml
