environments:
  kind:
    kubeContext: kind-kind-cluster
    values:
      - values.kind.yaml
---
repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts

releases:
  - name: reloader
    namespace: stakater
    chart: stakater/reloader
    version: 1.0.69
    values:
      - reloader.values.yaml.gotmpl
