environments:
  kind:
    kubeContext: kind-kind-cluster
    values:
      - values.kind.yaml
---
releases:
  - name: nginx-ingress
    namespace: nginx
    chart: oci://ghcr.io/nginxinc/charts/nginx-ingress
    version: 1.1.3
    values:
      - nginx-ingress.values.gotmpl
