apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: ca-bundle
  namespace: cert-manager
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        key: ca.crt
        selector:
          matchLabels:
            trust: enabled
  target:
    configMap:
      key: ca-certificates.crt
    namespaceSelector:
      matchLabels:
        trust: enabled
