apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: mtls-system
  labels:
    app: hello-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hello-app
          image: us-docker.pkg.dev/google-samples/containers/gke/hello-app-tls:1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000 # root
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
          env:
            - name: TLS_CERT
              value: /tls/tls.crt
            - name: TLS_KEY
              value: /tls/tls.key
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: tls
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: mtls-issuer
              csi.cert-manager.io/dns-names: >-
                hello-app,
                hello-app.mtls-system,
                hello-app.mtls-system.svc,
                hello-app.mtls-system.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: mtls-system
spec:
  selector:
    app: hello-app
  ports:
    - port: 443
      targetPort: 8443
