environments:
  kind:
    kubeContext: kind-kind-cluster
    values:
      - values.kind.yaml
---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.14.3
    values:
      - cert-manager.values.yaml.gotmpl

  - name: cert-manager-csi-driver
    namespace: cert-manager
    chart: jetstack/cert-manager-csi-driver
    version: 0.7.1
    needs:
      - cert-manager
    values:
      - cert-manager-csi-driver.yaml.gotmpl

  - name: trust-manager
    namespace: cert-manager
    chart: jetstack/trust-manager
    version: 0.8.0
    needs:
      - cert-manager
    values:
      - trust-manager.values.yaml.gotmpl
