cert-manager:
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
  webhook:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
  cainjector:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
  startupapicheck:
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
cert-manager-csi-driver:
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
trust-manager:
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
