environments:
  kind:
    kubeContext: kind-kind-cluster
    values:
      - values.kind.yaml
---
releases:
  - name: redis
    namespace: redis
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 18.17.1
    set:
      - name: auth.password
        value: '{{ env "REDIS_PASSWORD" }}'
    values:
      - redis.values.gotmpl
